"""coins table

Revision ID: 576f92b3a7c1
Revises: bc69fdbc307f
Create Date: 2018-01-31 17:07:24.452110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576f92b3a7c1'
down_revision = 'bc69fdbc307f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_amount'), 'coin', ['amount'], unique=False)
    op.create_index(op.f('ix_coin_symbol'), 'coin', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_symbol'), table_name='coin')
    op.drop_index(op.f('ix_coin_amount'), table_name='coin')
    op.drop_table('coin')
    # ### end Alembic commands ###
