"""change Coin model to use name of coin, not symbol

Revision ID: 71740d98cee0
Revises: 576f92b3a7c1
Create Date: 2018-02-01 20:47:38.316511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71740d98cee0'
down_revision = '576f92b3a7c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_coin_name'), 'coin', ['name'], unique=False)
    op.drop_index('ix_coin_symbol', table_name='coin')
    op.drop_column('coin', 'symbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('symbol', sa.VARCHAR(length=5), nullable=True))
    op.create_index('ix_coin_symbol', 'coin', ['symbol'], unique=1)
    op.drop_index(op.f('ix_coin_name'), table_name='coin')
    op.drop_column('coin', 'name')
    # ### end Alembic commands ###
